[tool.ruff]
line-length = 125
# Enable common rule sets: E (pycodestyle), F (pyflakes), I (isort), B (flake8-bugbear)
select = ["E", "F", "I", "B"]
ignore = [
    "B008", # allow function call as default arg (numpy/scipy random usage)
    "F405",
    "F403",
    "B007"
]
# Exclude virtual-envs etc.
exclude = [".venv", "venv", "build", "dist"]
