name: Python package – tests & lint

on:
  push:
    branches: ["main", "update_utils"]
  pull_request:
    branches: ["main", "update_utils"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff linter
        run: ruff check --output-format=github .

      - name: Execute Jupyter notebooks
        run: |
          # Install nbconvert for notebook execution
          pip install jupyter nbconvert
          # Execute all notebooks under src/ (fails CI on errors)
          for nb in $(find src -name "*.ipynb"); do
            jupyter nbconvert --to notebook --execute "$nb" --output ".executed-$(basename $nb)"
          done

      - name: Run tests
        run: pytest